name: Publish to PyPI
on:
  workflow_run:
    workflows: ["Run Tests"]
    types: [completed]
    branches: [master]

jobs:
  publish:
    name: Build and Publish to PyPI
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build package
        run: pip install build && python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
